#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    01                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/29 11:35:28 by jaleman           #+#    #+#              #
#    Updated: 2018/10/29 11:35:29 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Get the list of the network interfaces of the machine without displaying
# any detail for these interfaces.
# Only the list of names.
ifconfig -l | tr ' ' '\n'
