#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    04                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/29 12:07:00 by jaleman           #+#    #+#              #
#    Updated: 2018/10/29 12:07:00 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Identifiy the default gateway in the routing table

route -n get default | grep "gateway" | cut -d " " -f5-
