#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    04                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/29 21:56:48 by jaleman           #+#    #+#              #
#    Updated: 2018/10/29 21:56:49 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# What command gives you the time since your system was last booted?

uptime --since
