#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    10                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/29 22:43:01 by jaleman           #+#    #+#              #
#    Updated: 2018/10/29 22:43:01 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Name the command that lists the partition tables of external devices

fdisk -l

# For some reason, a regular user isn't able to run fdisk alone, but using
# the absolute path of the binary `/sbin/fdisk -l` works fine. lol
