#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    11                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaleman <jaleman@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/29 22:51:45 by jaleman           #+#    #+#              #
#    Updated: 2018/10/29 22:51:45 by jaleman          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Name the command that displays the available space left on the system

df -lh
